name: Release Widget

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      release_version:
        description: 'Release version (e.g., 1.2.3)'
        required: true
        type: string

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history to get the latest tag
          ref: gh-pages

      - name: Determine Release Version
        id: determine-release-version
        run: |
          if [[ -n "${{ github.event.inputs.release_version }}" ]]; then
            RELEASE_VERSION="${{ github.event.inputs.release_version }}"
          fi
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV

      - name: Get Repository Name
        id: repo-name
        run: |
          echo "REPO_NAME=$(basename $GITHUB_REPOSITORY)" >> $GITHUB_ENV

      - name: Rename Widget Folder
        run: |
          mv widget $REPO_NAME

      - name: Create Zip File
        run: |
          ZIP_FILE_NAME="$REPO_NAME-v$RELEASE_VERSION.zip"
          zip -r $ZIP_FILE_NAME $REPO_NAME
          echo "ZIP_FILE_NAME=$ZIP_FILE_NAME" >> $GITHUB_ENV

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 'v${{ env.RELEASE_VERSION }}'
          release_name: '${{ env.REPO_NAME }} v${{ env.RELEASE_VERSION }}'
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.ZIP_FILE_NAME }}
          asset_name: ${{ env.ZIP_FILE_NAME }}
          asset_content_type: application/zip
